### ISSUE TITLE
XML Export Kapa Planung funktioniert nicht

### ISSUE THREAD

**Issue by pefi1011** [pefi1011/ibsys2Tool#2]
![screen shot 2015-01-07 at 22 49 01](https://cloud.githubusercontent.com/assets/2700828/5653989/839755ee-96bf-11e4-9c17-ac5c8e585611.png)

Dazu generierter XML

![screen shot 2015-01-07 at 22 50 46](https://cloud.githubusercontent.com/assets/2700828/5654008/a8b504de-96bf-11e4-92e9-60663420337c.png)

**Comment by diva1012** [comment]
Bei mir funktioniert es... ich konnte den Fehler nicht produzieren

**Comment by pefi1011** [comment]
Wir lassen noch Torben testen und machen dann Issue auf Closed
